#!/bin/bash

# Small script to CommIt-PUsh-POst, requires xclip

declare -r TEXT="Please go to http://github.com/ajlyon/zotero-bits/raw/master/%s and save the file to the translators directory of your Zotero data directory (http://www.zotero.org/support/zotero_data).

It should start working again. If this works for you, please post here so that I can submit this change to be pushed to all users."

if (! git commit "$1")
	then
	echo Commit failed. Possibly no changes?
fi	
if (git push origin master)
	then
	echo Pushed changes.
fi
printf "$TEXT" $(python -c "import urllib; print urllib.quote('''$1''')") | xclip -sel clip

echo Message copied to clipboard.
