#!/bin/bash

declare -r TEXT="The style named %s has the ID %s and it depends on the style withe ID %s"

if [ -f $3.csl ]
then
	echo Target file $3.csl already exists.
	exit
fi

printf "$TEXT" "$2" "$3" "$1" > $3.csl

echo Style $3.csl created for $2, dependent on style $1
