#!/bin/bash

if [ $# -ne 5 ] 
then
	echo Usage: depend parent-style \"New Style\" new-style citation-format field.
	echo Does not support multiple fields. Sorry.
	exit
fi

declare -r TEXT=$(cat <<'HEREDOC'
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0">
   <info>
      <title>%s</title>
      <id>http://www.zotero.org/styles/%s</id>
      <link href="http://www.zotero.org/styles/%s" rel="independent-parent"/>
      <category citation-format="%s"/>
      <category field="%s"/>
      <updated/>
   </info>
</style>
HEREDOC
)

if [ -f $3.csl ]
then
	echo Target file $3.csl already exists.
	exit
fi

printf "$TEXT" "$2" "$3" "$1" "$4" "$5" > $3.csl

echo Created $3.csl for $2, dependent on style $1: $4, $5
