pref("extensions.zotfile.source_dir","~/Downloads");
pref("extensions.zotfile.dest_dir", "~/Documents/Literatur");
pref("extensions.zotfile.useZoteroToRename", false);
pref("extensions.zotfile.renameFormat", "%a_%y_%t");
pref("extensions.zotfile.renameFormat_patent", "%a_%y_%t");
pref("extensions.zotfile.max_titlelength", 80);
pref("extensions.zotfile.max_authors", 2);
pref("extensions.zotfile.add_etal", true);
pref("extensions.zotfile.etal", " et al");
pref("extensions.zotfile.confirmation", true);
pref("extensions.zotfile.confirmation_batch", 2);
pref("extensions.zotfile.import", false);
pref("extensions.zotfile.replace_blanks", false);
pref("extensions.zotfile.subfolder", false);
pref("extensions.zotfile.subfolderFormat", "/%w/%y");
pref("extensions.zotfile.converterPath", "c:\\Documents and Settings\\Avram\\My Documents\\Academic Large Documents\\Tethered Shooting\\process.bat");
pref("extensions.zotfile.fileTypes", "pdf|doc|txt|rtf|jpg|djvu");
pref("extensions.zotfile.attachOriginal", true);
pref("extensions.zotfile.promptForDetails", true);
